#!/usr/bin/env python3
"""Rewrite the header and footer of every page from tools/site_chrome.py.

    python3 tools/apply_chrome.py          # rewrite every page
    python3 tools/apply_chrome.py --check  # report drift, change nothing

The site has no build step, so the navigation is duplicated into every file. The
cost of that is drift: change the ribbon and ten pages disagree until each one
is edited. This tool is the answer. One source, applied everywhere, and --check
in the site check catches a page that fell behind.
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import site_chrome as chrome  # noqa: E402

SKIP_DIRS = {".git", "pipeline", "docs", "node_modules", "assets"}
HEADER = re.compile(r'<header class="site-head">.*?</header>\n', re.DOTALL)
FOOTER = re.compile(r'<footer class="site-foot"[^>]*>.*?</footer>\n', re.DOTALL)
# The stylesheet link lives in <head>, which the header replacement does not
# reach, so its cache busting version is rewritten separately.
STYLES = re.compile(r'href="((?:\.\./)*assets/styles\.css)(?:\?v=[^"]*)?"')
# Chapter 14 of the Master Operations Handbook requires a slug on every page, and
# the publication gate checks the canonical link against where the file sits. The
# rendered article pages get theirs from tools/render_article.py; the hand written
# pages get theirs here, so one tool owns it for the whole site.
CANONICAL = re.compile(r'<link rel="canonical" href="[^"]*">\n')
THEME = re.compile(r'<meta name="theme-color" content="[^"]*">\n')
ROBOTS = re.compile(r'<meta name="robots" content="[^"]*">\n')


def pages():
    out = []
    for base, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            if f.endswith(".html"):
                out.append(os.path.join(base, f))
    return sorted(out)


def rel_for(path):
    depth = os.path.relpath(path, ROOT).count(os.sep)
    return "../" * depth


def write_robots_txt(check_only):
    """robots.txt, generated from the same switch as the page level directive.

    A page meta tag and a robots.txt that disagree is worse than either alone,
    so both come from pipeline/config/site.json and both are written here.
    """
    cfg = chrome.site_config()
    path = os.path.join(ROOT, "robots.txt")
    if cfg.get("discoverable"):
        body = ("# Generated by tools/apply_chrome.py from pipeline/config/site.json.\n"
                "User-agent: *\n"
                "Allow: /\n"
                "Sitemap: %ssitemap.xml\n" % cfg["base_url"])
    else:
        body = ("# Generated by tools/apply_chrome.py from pipeline/config/site.json.\n"
                "# The site is published and not publicised: every page is an editorial\n"
                "# draft that has not been evidence verified or consultant reviewed, and\n"
                "# indexing it would publicise it. Set discoverable true in site.json and\n"
                "# run this tool again when that changes. See decision 015.\n"
                "User-agent: *\n"
                "Disallow: /\n")
    existing = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            existing = fh.read()
    if existing == body:
        return
    if check_only:
        print("  DRIFTED  robots.txt")
        return
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    print("  updated  robots.txt")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report pages whose chrome has drifted, and change nothing")
    args = ap.parse_args()

    changed, drifted, skipped, missing_head = [], [], [], []
    for path in pages():
        rel = rel_for(path)
        with open(path, encoding="utf-8") as fh:
            original = fh.read()

        if not HEADER.search(original) or not FOOTER.search(original):
            skipped.append(os.path.relpath(path, ROOT))
            continue

        version = chrome.stylesheet_version()
        updated = STYLES.sub(lambda m: 'href="%s?v=%s"' % (m.group(1), version), original)
        updated = HEADER.sub(lambda m: chrome.header(rel), updated, count=1)
        # the footer template closes the document, so anything after it goes
        updated = FOOTER.sub(lambda m: chrome.footer(rel), updated, count=1)
        updated = re.sub(r'(</footer>\n).*\Z', r'\1\n</body>\n</html>\n', updated,
                         flags=re.DOTALL)

        # The theme colour is the one colour literal outside the stylesheet, so
        # it is driven from pipeline/config/site.json and refreshed here rather
        # than left to drift page by page.
        theme = '<meta name="theme-color" content="%s">\n' % chrome.site_config()["theme_color"]
        if THEME.search(updated):
            updated = THEME.sub(theme, updated, count=1)

        # The site is published and not publicised while site.json says so, and
        # that posture has to be the same on every page or it is not a posture.
        robots = chrome.robots_meta()
        robots = (robots + "\n") if robots else ""
        if ROBOTS.search(updated):
            updated = ROBOTS.sub(robots, updated, count=1)
        elif robots and THEME.search(updated):
            updated = THEME.sub(lambda m: m.group(0) + robots, updated, count=1)

        want = '<link rel="canonical" href="%s">\n' % chrome.canonical_url(
            os.path.relpath(path, ROOT))
        if CANONICAL.search(updated):
            updated = CANONICAL.sub(want, updated, count=1)
        elif THEME.search(updated):
            updated = THEME.sub(lambda m: m.group(0) + want, updated, count=1)
        else:
            missing_head.append(os.path.relpath(path, ROOT))

        if updated == original:
            continue
        if args.check:
            drifted.append(os.path.relpath(path, ROOT))
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(updated)
            changed.append(os.path.relpath(path, ROOT))

    write_robots_txt(args.check)

    for name in skipped:
        print("  skipped (no header or footer to replace): %s" % name)
    for name in missing_head:
        print("  no theme-color meta to anchor the canonical link: %s" % name)
    if args.check:
        for name in drifted:
            print("  DRIFTED  %s" % name)
        print("%d page(s) out of step with tools/site_chrome.py" % len(drifted))
        return 1 if drifted else 0
    for name in changed:
        print("  updated  %s" % name)
    print("%d page(s) rewritten, %d already current" % (changed.__len__(),
                                                        len(pages()) - len(changed) - len(skipped)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
