#!/usr/bin/env python3
"""The position register: every sentence that tells a clinician what to do.

    python3 tools/positions.py --extract          # rebuild registers from the pages
    python3 tools/positions.py --report           # the sign off list, grouped by page
    python3 tools/positions.py --report --unsigned

A page describing where the popliteal artery lies is anatomy. A page saying
"treat loss of foot pulses as arterial until proven otherwise" is clinical
advice, and it is advice nobody has signed. Section 2 turned out to contain
forty nine such sentences rather than the one that was noticed, which is why
this is a register rather than a list in a review pack.

The detector is a heuristic over imperative openers and directed modals, so it
over collects. That is deliberate: a false positive costs a reviewer one line,
and a false negative puts unsigned advice on a professional page. The reviewer
reclassifies anything that is teaching rather than clinical direction.
"""

import argparse
import collections
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "pipeline", "functions", "style_lint"))
import linter  # noqa: E402

RUNS = os.path.join(ROOT, "pipeline", "runs")
BRIEFS = os.path.join(ROOT, "pipeline", "config", "briefs")
REGISTRY = os.path.join(ROOT, "pipeline", "config", "positions")
FRESH = "UNSIGNED"
STATES = ("UNSIGNED", "CONFIRMED", "AMENDED", "WITHDRAWN", "NOT_CLINICAL")


def sort_key(page_id):
    return [(0, int(p)) if p.isdigit() else (1, 0, p) for p in str(page_id).split(".")]


def sentences(page_id):
    path = os.path.join(RUNS, page_id, "styled_v1.md")
    if not os.path.exists(path):
        return None
    raw = open(path).read().split("## References")[0]
    tier, section = None, None
    out = []
    for block in raw.split("\n\n"):
        head = re.match(r"^\s{0,3}(#{1,3})\s+(.+?)\s*$", block.strip())
        if head:
            title = linter.normalise_title(head.group(2))
            if len(head.group(1)) == 2:
                tier, section = linter.tier_by_heading().get(title, tier), None
            elif len(head.group(1)) == 3:
                section = head.group(2).strip()
            continue
        flat = re.sub(r"\s+", " ", block.lstrip("- ")).strip()
        for sent in re.split(r"(?<=[.!?]) ", flat):
            out.append((sent.strip(), tier, section))
    return out


def detect(sent):
    if len(sent.split()) < 6 or linter.POSITION_NOISE.search(sent):
        return None
    if linter.POSITION_OPENER.search(sent):
        return "imperative"
    if linter.POSITION_MODAL.search(sent):
        return "directed modal"
    return None


WITHDRAWN_NOTE = ("No longer on the page; kept so the record of what was signed "
                  "survives.")


def merge(page_id, found):
    path = os.path.join(REGISTRY, "%s.json" % page_id)
    prior = {}
    if os.path.exists(path):
        for e in json.load(open(path)).get("positions") or []:
            prior[normalise(e.get("as_written", ""))] = e
    out, seen = [], set()
    for e in found:
        key = normalise(e["as_written"])
        if key in seen:
            continue
        seen.add(key)
        was = prior.get(key)
        if was:
            # the reviewer's verdict, classification and note are theirs
            for field in ("verification", "kind", "signed_off_by", "note"):
                if field in was:
                    e[field] = was[field]
        out.append(e)
    for key, was in prior.items():
        if key in seen:
            continue
        was["verification"] = "WITHDRAWN"
        # Appended only once. This used to concatenate on every extraction, so a
        # withdrawn position's note grew by one copy of the sentence per run and
        # had reached twenty four copies on 3.11.9 before anyone read it. The
        # extractor runs on every chapter build, so a non idempotent write here
        # also meant a clean checkout went dirty whenever the registers were
        # re-extracted, which is how it was found.
        note = (was.get("note") or "").strip()
        if WITHDRAWN_NOTE not in note:
            was["note"] = (note + " " + WITHDRAWN_NOTE).strip()
        out.append(was)
    return out


def normalise(text):
    return re.sub(r"\s+", " ", str(text)).strip().lower()


def write(page_id, positions):
    brief = json.load(open(os.path.join(BRIEFS, "%s.json" % page_id)))
    body = collections.OrderedDict([
        ("register_version", "1.0"),
        ("page_id", page_id),
        ("title", brief["title"]),
        ("source_of_truth", "docs/decisions/007-clinical-positions-need-signing.md"),
        ("note", "Generated by tools/positions.py --extract from the page itself. Edit the "
                 "verification, kind, signed_off_by and note fields; everything else is "
                 "rewritten on the next extraction. The detector over collects on purpose: "
                 "mark anything that is teaching rather than clinical direction as "
                 "NOT_CLINICAL rather than deleting it."),
        ("states", list(STATES)),
        ("positions", positions),
    ])
    with open(os.path.join(REGISTRY, "%s.json" % page_id), "w") as fh:
        fh.write(json.dumps(body, indent=2) + "\n")


def cmd_extract():
    total, pages = 0, 0
    for page_id in sorted(os.listdir(RUNS), key=sort_key):
        if not os.path.isdir(os.path.join(RUNS, page_id)):
            continue
        sents = sentences(page_id)
        if sents is None:
            continue
        brief_path = os.path.join(BRIEFS, "%s.json" % page_id)
        if not os.path.exists(brief_path):
            continue
        tiers = json.load(open(brief_path)).get("tiers_required") or []
        # a page with no professional tier gives no clinical direction to a clinician
        if not set(tiers) & {"medical_student", "mrcs", "frcs", "fellowship", "consultant"}:
            continue
        found = []
        for sent, tier, section in sents:
            kind = detect(sent)
            if not kind:
                continue
            found.append(collections.OrderedDict([
                ("as_written", sent), ("tier", tier), ("section", section),
                ("detected_as", kind), ("kind", "CLINICAL_RECOMMENDATION"),
                ("verification", FRESH), ("signed_off_by", ""),
            ]))
        if not found and not os.path.exists(os.path.join(REGISTRY, "%s.json" % page_id)):
            continue
        positions = merge(page_id, found)
        write(page_id, positions)
        live = [p for p in positions if p["verification"] != "WITHDRAWN"]
        total += len(live)
        pages += 1
        print("%-7s %2d position(s)" % (page_id, len(live)))
    print("%d positions registered across %d pages" % (total, pages))


def cmd_report(unsigned_only):
    rows, counts = [], collections.Counter()
    for name in sorted(os.listdir(REGISTRY), key=lambda n: sort_key(n[:-5])):
        if not name.endswith(".json"):
            continue
        reg = json.load(open(os.path.join(REGISTRY, name)))
        for pos in reg.get("positions") or []:
            counts[pos["verification"]] += 1
            if unsigned_only and pos["verification"] != FRESH:
                continue
            rows.append((reg["page_id"], reg["title"], pos))
    page = None
    for page_id, title, pos in rows:
        if page_id != page:
            print("\n%s  %s" % (page_id, title))
            page = page_id
        print("  [%-10s] %s" % (pos.get("tier") or "", pos["as_written"][:118]))
    print()
    for state, n in sorted(counts.items()):
        print("%-24s %d" % (state, n))
    print("%-24s %d" % ("total", sum(counts.values())))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--extract", action="store_true")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--unsigned", action="store_true")
    args = ap.parse_args()
    if args.extract:
        cmd_extract()
    if args.report or not args.extract:
        cmd_report(args.unsigned)


if __name__ == "__main__":
    main()
