"""Consultant review packs, one per chapter, generated from the work.

EV-2 is the oldest blocker on this build: the reviewers exist and the route for
their decisions does not. The registers hold 523 unsigned recommendations and 254
unchecked measurements, and handing a consultant a list of 523 is handing them
nothing. A chapter is a unit a person can actually sit down with.

So a pack is generated per chapter and it is machine readable in both
directions. Generating it writes a markdown file whose tables carry a stable
reference per row. Ingesting it reads the Decision and Reviewer columns back into
pipeline/config/positions/<page>.json and pipeline/config/figures/<page>.json.
Nothing in a pack is written by hand, which is the same rule the figure and
position registers follow: the list comes from the work rather than from a
person compiling it.

    python3 tools/review_pack.py --chapter 3.3
    python3 tools/review_pack.py --chapter 3.3 --format all
    python3 tools/review_pack.py --all
    python3 tools/review_pack.py --status
    python3 tools/review_pack.py --ingest docs/review/packs/chapter-3.3.xlsx

A pack comes in three formats and the markdown one is the default. The
spreadsheet is what a consultant filling eighty five cells actually wants, and
the Word file is what gets printed and taken into a meeting. All three carry the
same rows and the same row references, and --ingest reads any of them.

The spreadsheet and the Word file need openpyxl and python-docx:

    pip install openpyxl python-docx

They are not generated by --all, because both formats embed a timestamp and
regenerating fifty binaries on every run would churn the repository. Ask for a
chapter by name when a pack is going out.
"""

import argparse
import collections
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = os.path.join(ROOT, "pipeline", "runs")
BRIEFS = os.path.join(ROOT, "pipeline", "config", "briefs")
POSITIONS = os.path.join(ROOT, "pipeline", "config", "positions")
FIGURES = os.path.join(ROOT, "pipeline", "config", "figures")
PUBLISHED = os.path.join(ROOT, "pipeline", "config", "published_pages.json")
OUTLINE = os.path.join(ROOT, "pipeline", "config", "architecture", "outline_1_to_15.json")
PACKS = os.path.join(ROOT, "docs", "review", "packs")

# A row reference has to survive a round trip through a text editor and a
# spreadsheet, so it is short, has no spaces, and names the register it belongs
# to: P for a position, F for a figure, then the row's index in that file.
REF = re.compile(r"^([0-9]+(?:\.[0-9]+){2})-([PF])([0-9]+)$")

FIGURE_STATES = ["UNVERIFIED_FROM_MEMORY", "VERIFIED", "CORRECTED", "REMOVED"]


def page_sort_key(page_id):
    return tuple(int(x) for x in page_id.split("."))


def chapter_of(page_id):
    return page_id.rsplit(".", 1)[0]


def published():
    with open(PUBLISHED, encoding="utf-8") as fh:
        data = json.load(fh)
    return data["pages"] if "pages" in data else data


def chapter_names():
    with open(OUTLINE, encoding="utf-8") as fh:
        data = json.load(fh)
    out = {}
    for c in data.get("chapters", []):
        cid = str(c.get("chapter_id") or c.get("id") or "")
        if cid:
            out[cid] = c.get("name") or ""
    return out


def load(path):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def page_facts(page_id):
    """Everything the pack states about one page, read from that page's own files."""
    brief = load(os.path.join(BRIEFS, "%s.json" % page_id)) or {}
    lint = load(os.path.join(RUNS, page_id, "lint_report.json")) or {}
    handoff = load(os.path.join(RUNS, page_id, "draft_v1.handoff.json")) or {}
    doc = lint.get("document", {})
    findings = lint.get("findings", [])
    return {
        "page_id": page_id,
        "title": brief.get("title", ""),
        "page_type": brief.get("page_type", ""),
        "tiers": brief.get("tiers_required", []),
        "words": doc.get("word_count", 0),
        "fails": len([f for f in findings if f.get("severity") == "fail"]),
        "warns": len([f for f in findings if f.get("severity") not in ("fail", None)]),
        "claims": handoff.get("claims_needing_verification", []),
        "positions": (load(os.path.join(POSITIONS, "%s.json" % page_id)) or {}).get(
            "positions", []),
        "figures": (load(os.path.join(FIGURES, "%s.json" % page_id)) or {}).get(
            "figures", []),
    }


def chapter_pages(chapter):
    pages = [p for p in published() if chapter_of(p) == chapter]
    return sorted(pages, key=page_sort_key)


def chapters_with_pages():
    seen = {chapter_of(p) for p in published()}
    return sorted(seen, key=lambda c: tuple(int(x) for x in c.split(".")))


def cell(text):
    """A table cell that cannot break the table it sits in."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def pack_path(chapter, fmt="md"):
    return os.path.join(PACKS, "chapter-%s.%s" % (chapter, fmt))


def build(chapter, names):
    pages = chapter_pages(chapter)
    if not pages:
        return None
    facts = [page_facts(p) for p in pages]
    name = names.get(chapter, "")
    section = chapter.split(".")[0]
    pub = published()

    words = sum(f["words"] for f in facts)
    fails = sum(f["fails"] for f in facts)
    warns = sum(f["warns"] for f in facts)
    types = sorted({f["page_type"] for f in facts if f["page_type"]})
    tiers = []
    for f in facts:
        for t in f["tiers"]:
            if t not in tiers:
                tiers.append(t)
    unsigned = [(f, i, p) for f in facts for i, p in enumerate(f["positions"], 1)
                if p.get("verification") == "UNSIGNED"]
    unchecked = [(f, i, g) for f in facts for i, g in enumerate(f["figures"], 1)
                 if g.get("verification") == "UNVERIFIED_FROM_MEMORY"]

    meta = {
        "chapter": chapter, "name": name, "section": section, "facts": facts,
        "published": pub, "pages": len(facts), "words": format(words, ","),
        "types": ", ".join(types) or "not stated",
        "tiers": ", ".join(t.replace("_", " ") for t in tiers) or "not stated",
        "gate": ("all pages pass, %d warnings" % warns if not fails
                 else "%d failures" % fails),
        "unsigned": unsigned, "unchecked": unchecked,
    }

    out = []
    w = out.append
    w("# Consultant review pack: chapter %s %s" % (chapter, name))
    w("")
    w("Generated by `tools/review_pack.py --chapter %s`. Do not edit by hand except "
      "in the Decision and Reviewer columns: regenerating this file rewrites "
      "everything else." % chapter)
    w("")
    w("| Field | Value |")
    w("|---|---|")
    w("| Section | %s |" % section)
    w("| Chapter | %s %s |" % (chapter, name))
    w("| Pages | %d |" % len(facts))
    w("| Page type | %s |" % (", ".join(types) or "not stated"))
    w("| Tiers | %s |" % (", ".join(t.replace("_", " ") for t in tiers) or "not stated"))
    w("| Words | %s |" % format(words, ","))
    w("| Style gate | %s |" % ("all pages pass, %d warnings" % warns if not fails
                               else "%d failures" % fails))
    w("| Evidence verification | did not run on any page |")
    w("| Measurements to check | %d |" % len(unchecked))
    w("| Recommendations to sign | %d |" % len(unsigned))
    w("")
    w("## What has not happened")
    w("")
    w("No source was retrieved for any page in this chapter. The build environment "
      "has no access to PubMed, Cochrane, a journal or a textbook, so agent 2 of the "
      "pipeline, the fact checker, could not run. Every page carries "
      "`NOT_RUN_TOOLS_UNAVAILABLE` in its verified handoff.")
    w("")
    w("This pack is therefore standing in for the verification stage as well as for "
      "the review stage. A claim here has been checked by nobody.")
    w("")
    w("## The pages")
    w("")
    w("| Page | Title | Tiers | Words | Published as |")
    w("|---|---|---|---|---|")
    for f in facts:
        w("| %s | %s | %d | %s | `%s` |"
          % (f["page_id"], cell(f["title"]), len(f["tiers"]), format(f["words"], ","),
             pub.get(f["page_id"], "")))
    w("")
    w("## Claims to confirm")
    w("")
    w("The deepest tier's key learning points on each page, which are the chapter's "
      "substantive claims. Every other statement in the body needs the same check; "
      "these are where to start.")
    w("")
    for f in facts:
        if not f["claims"]:
            continue
        w("**%s %s**" % (f["page_id"], f["title"]))
        w("")
        for c in f["claims"]:
            w("- %s" % c)
        w("")
    w("## Measurements")
    w("")
    if unchecked:
        w("Every figure below was written from standard teaching and none has a source "
          "against it. Put `VERIFIED` with a source, `CORRECTED` with the right value, or "
          "`REMOVED` to take it off the page.")
        w("")
        w("| Ref | Page | Tier | Figure | The sentence it supports | Decision | Source |")
        w("|---|---|---|---|---|---|---|")
        for f, i, g in unchecked:
            w("| %s-F%d | %s | %s | %s | %s |  |  |"
              % (f["page_id"], i, f["page_id"], g.get("tier", ""),
                 cell(g.get("as_written", "")), cell(g.get("claim", ""))))
        w("")
        w("Allowed decisions: `%s`." % "`, `".join(FIGURE_STATES[1:]))
    else:
        w("No unchecked measurement in this chapter.")
    w("")
    w("## Recommendations")
    w("")
    if unsigned:
        w("Each sentence below tells a clinician what to do, on a page that carries no "
          "name. The detector over collects on purpose, so a sentence that is teaching "
          "rather than clinical direction is marked `NOT_CLINICAL` rather than argued "
          "about.")
        w("")
        w("| Ref | Page | Tier | Sentence | Decision | Reviewer |")
        w("|---|---|---|---|---|---|")
        for f, i, p in unsigned:
            w("| %s-P%d | %s | %s | %s |  |  |"
              % (f["page_id"], i, f["page_id"], p.get("tier", ""),
                 cell(p.get("as_written", ""))))
        w("")
        w("Allowed decisions: `CONFIRMED`, `AMENDED`, `WITHDRAWN`, `NOT_CLINICAL`.")
    else:
        w("No unsigned recommendation in this chapter.")
    w("")
    w("## How to return this")
    w("")
    w("1. Fill the Decision column on any row you have an answer for. Leave the rest "
      "blank; a blank row stays outstanding and comes back in the next pack.")
    w("2. Put your name in the Reviewer column, and a source in the Source column for "
      "a measurement.")
    w("3. Send the file back, then run:")
    w("")
    w("       python3 tools/review_pack.py --ingest docs/review/packs/chapter-%s.md"
      % chapter)
    w("")
    w("That writes each decision into the page's own register. The style gate then "
      "enforces it: a page carrying a recommendation that is not in its register "
      "fails POS-001, and a figure that is not in its register fails FIG-002, so a "
      "signed chapter cannot drift back to unsigned without the gate saying so.")
    w("")
    w("Amending a sentence or correcting a figure needs the page edited as well as "
      "the register. Put the replacement wording in the Decision cell after "
      "`AMENDED:` or `CORRECTED:` and it is carried into the register's note field "
      "for whoever makes the edit.")
    w("")
    w("## The same pack in two other formats")
    w("")
    w("A spreadsheet, which is easier to fill, and a Word file, which is easier "
      "to print:")
    w("")
    w("       python3 tools/review_pack.py --chapter %s --format all" % chapter)
    w("")
    w("All three carry the same rows and the same references, and `--ingest` "
      "reads any of them.")
    w("")
    meta["markdown"] = "\n".join(out) + "\n"
    return meta


def files_module():
    """Imported late and by name, so the markdown path needs nothing installed."""
    try:
        import review_pack_files
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise SystemExit(
            "the spreadsheet and Word formats need openpyxl and python-docx:\n"
            "    pip install openpyxl python-docx\n"
            "(%s)" % exc)
    return review_pack_files


def write_pack(chapter, names, check_only=False, formats=("md",)):
    meta = build(chapter, names)
    if meta is None:
        return "skipped"
    if not os.path.isdir(PACKS):
        os.makedirs(PACKS)

    results = []
    if "md" in formats:
        path = pack_path(chapter)
        old = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                old = fh.read()
        if old == meta["markdown"]:
            results.append("current")
        elif check_only:
            results.append("drifted")
        else:
            with io.open(path, "w", encoding="utf-8") as fh:
                fh.write(meta["markdown"])
            results.append("written")

    # A binary pack is never compared with what is on disk, because openpyxl and
    # python-docx both embed a timestamp: two identical runs differ byte for
    # byte, so "drifted" would be meaningless here.
    if not check_only:
        for fmt in ("xlsx", "docx"):
            if fmt not in formats:
                continue
            mod = files_module()
            path = pack_path(chapter, fmt)
            (mod.write_xlsx if fmt == "xlsx" else mod.write_docx)(path, meta)
            results.append("written")

    if "drifted" in results:
        return "drifted"
    if "written" in results:
        return "written"
    return "current"


ROW = re.compile(r"^\|\s*([^|]+?)\s*\|(.*)\|\s*$")


def parse_rows(text):
    """Every table row whose first cell is a row reference."""
    out = []
    for line in text.splitlines():
        m = ROW.match(line)
        if not m:
            continue
        ref = REF.match(m.group(1).strip())
        if not ref:
            continue
        cells = [c.strip() for c in m.group(2).split("|")]
        out.append((ref.group(1), ref.group(2), int(ref.group(3)), cells))
    return out


def rows_from(path):
    """The referenced rows of a pack, whichever of the three formats it is in.

    Every format puts the same columns in the same order after the reference, so
    one reader serves all three. The spreadsheet and the Word file add a Note
    column on the end, which the markdown pack does not have.
    """
    ext = os.path.splitext(path)[1].lower()
    if ext in (".md", ".markdown", ".txt"):
        with open(path, encoding="utf-8") as fh:
            return parse_rows(fh.read())
    if ext in (".xlsx", ".xlsm"):
        raw = files_module().read_xlsx(path)
    elif ext == ".docx":
        raw = files_module().read_docx(path)
    else:
        raise SystemExit("not a pack this can read: %s\n"
                         "expected .md, .xlsx or .docx" % os.path.basename(path))
    out = []
    for ref, cells in raw:
        m = REF.match(ref.strip())
        if m:
            out.append((m.group(1), m.group(2), int(m.group(3)), cells))
    return out


def ingest(path):
    rows = rows_from(path)
    if not rows:
        print("no referenced rows found in %s" % os.path.relpath(path, ROOT))
        return 1

    applied, blank, errors = [], 0, []
    # A register is loaded once, changed, then written once, so a malformed row
    # later in the file cannot leave a half written register behind.
    pending = {}

    for page_id, kind, index, cells in rows:
        if kind == "P":
            reg_path = os.path.join(POSITIONS, "%s.json" % page_id)
            key, states = "positions", ["CONFIRMED", "AMENDED", "WITHDRAWN", "NOT_CLINICAL"]
            decision = cells[3] if len(cells) > 3 else ""
            who = cells[4] if len(cells) > 4 else ""
            note = cells[5] if len(cells) > 5 else ""
        else:
            reg_path = os.path.join(FIGURES, "%s.json" % page_id)
            key, states = "figures", FIGURE_STATES[1:]
            decision = cells[4] if len(cells) > 4 else ""
            who = cells[5] if len(cells) > 5 else ""
            note = cells[6] if len(cells) > 6 else ""
        if not decision:
            blank += 1
            continue
        if reg_path not in pending:
            reg = load(reg_path)
            if reg is None:
                errors.append("%s-%s%d: no register at %s"
                              % (page_id, kind, index, os.path.relpath(reg_path, ROOT)))
                continue
            pending[reg_path] = reg
        reg = pending[reg_path]
        rowset = reg.get(key, [])
        if not 1 <= index <= len(rowset):
            errors.append("%s-%s%d: the register has %d rows"
                          % (page_id, kind, index, len(rowset)))
            continue
        verdict, _, detail = decision.partition(":")
        verdict = verdict.strip().upper()
        if verdict not in states:
            errors.append("%s-%s%d: %r is not one of %s"
                          % (page_id, kind, index, decision, ", ".join(states)))
            continue
        entry = rowset[index - 1]
        entry["verification"] = verdict
        if kind == "P":
            entry["signed_off_by"] = who
        else:
            entry["source"] = who
        wording = note.strip() or detail.strip()
        if wording:
            entry["note"] = wording
        applied.append("%s-%s%d %s" % (page_id, kind, index, verdict))

    if errors:
        for e in errors:
            print("  ERROR  %s" % e)
        print("")
        print("nothing written: %d row(s) could not be applied" % len(errors))
        return 1

    for reg_path, reg in sorted(pending.items()):
        with io.open(reg_path, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(reg, indent=2, ensure_ascii=False) + "\n")

    for a in applied:
        print("  applied  %s" % a)
    print("")
    print("%d decision(s) written into %d register(s), %d row(s) still blank"
          % (len(applied), len(pending), blank))
    return 0


def status(names):
    rows = []
    for chapter in chapters_with_pages():
        facts = [page_facts(p) for p in chapter_pages(chapter)]
        pos = [p for f in facts for p in f["positions"]]
        fig = [g for f in facts for g in f["figures"]]
        rows.append((chapter, names.get(chapter, ""), len(facts),
                     len([p for p in pos if p.get("verification") == "UNSIGNED"]), len(pos),
                     len([g for g in fig
                          if g.get("verification") == "UNVERIFIED_FROM_MEMORY"]), len(fig),
                     os.path.exists(pack_path(chapter))))
    print("%-7s %-38s %5s %12s %12s %5s" % ("chapter", "name", "pages", "unsigned",
                                            "unchecked", "pack"))
    for c, n, pages, unsigned, pos, unchecked, fig, has in rows:
        print("%-7s %-38s %5d %6d/%-5d %6d/%-5d %5s"
              % (c, n[:38], pages, unsigned, pos, unchecked, fig, "yes" if has else "no"))
    print("")
    print("%d chapters, %d unsigned of %d recommendations, %d unchecked of %d measurements"
          % (len(rows), sum(r[3] for r in rows), sum(r[4] for r in rows),
             sum(r[5] for r in rows), sum(r[6] for r in rows)))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--chapter", help="generate the pack for one chapter, e.g. 3.3")
    ap.add_argument("--all", action="store_true", help="generate a pack for every chapter")
    ap.add_argument("--check", action="store_true",
                    help="report packs that have drifted, and change nothing")
    ap.add_argument("--status", action="store_true", help="what is outstanding, by chapter")
    ap.add_argument("--ingest", metavar="PACK",
                    help="read decisions back from a filled pack, in any format")
    ap.add_argument("--format", default="md",
                    help="md (the default), xlsx, docx, all, or a comma separated list")
    args = ap.parse_args()

    formats = ["md", "xlsx", "docx"] if args.format == "all" else [
        f.strip() for f in args.format.split(",") if f.strip()]
    unknown = [f for f in formats if f not in ("md", "xlsx", "docx")]
    if unknown:
        ap.error("unknown format(s): %s" % ", ".join(unknown))
    if args.all and set(formats) != {"md"}:
        ap.error("--all generates markdown only; name a chapter for the other formats")

    names = chapter_names()
    if args.ingest:
        return ingest(args.ingest)
    if args.status:
        return status(names)
    if args.chapter:
        targets = [args.chapter]
    elif args.all or args.check:
        targets = chapters_with_pages()
    else:
        ap.print_help()
        return 1

    counts = collections.Counter()
    for chapter in targets:
        result = write_pack(chapter, names, check_only=args.check, formats=formats)
        counts[result] += 1
        if result in ("written", "drifted"):
            for fmt in formats:
                if fmt != "md" and args.check:
                    continue
                print("  %-8s docs/review/packs/chapter-%s.%s" % (result, chapter, fmt))
        elif result == "skipped":
            print("  skipped  chapter %s has no published page" % chapter)
    print("")
    print(", ".join("%d %s" % (n, k) for k, n in sorted(counts.items())))
    return 1 if counts["drifted"] else 0


if __name__ == "__main__":
    sys.exit(main())
